// frontend/src/components/BoxResults.vue
<script setup>
const props = defineProps({
  results: {
    length: Number,
    width: Number,
    height: Number
  },
  thickn: Number,
  boxStyle: String,
  formValid: Boolean
})

const calculateFormat = () => {
  const { length, width, height } = props.results
  const { thickn, boxStyle } = props

  // Calculate flap height based on material thickness
  let flapHeight
  if (thickn === 5) {
    flapHeight = width / 2 + 4
  } else if (thickn === 4) {
    flapHeight = width / 2 + 2
  } else {
    flapHeight = width / 2 + 1
  }

  // Blank Size Calculation based on Box Style and thickness
  // +38 = 40 glueFlap and -2 from length
  const boxLength = length + width + thickn * 2
  let format
  switch (boxStyle) {
    case 'box':
      format = `${boxLength * 2 + 38} x ${height + (thickn + flapHeight) * 2}`
      break
    case 'box-open':
      format = `${boxLength * 2 + 38} x ${height + thickn + flapHeight}`
      break
    case 'half':
      format = `${boxLength + 40} x ${height + (thickn + flapHeight) * 2}`
      break
    case 'half-open':
      format = `${boxLength + 40} x ${height + thickn + flapHeight}`
      break
    default:
      format = `${boxLength * 2 + 38} x ${height + (thickn + flapHeight) * 2}`
  }
  return format
}
// Get Material Function
const getMat = () => {
  const mapping = {
    5: 'BC',
    4: 'C',
    3: 'B'
  }
  return mapping[props.thickn] || ''
}
</script>

<template>
  <div class="">
    <div class="results" :style="{ opacity: formValid ? 1 : 0 }">
      <p>
        <strong>Outer Dimensions {{ getMat() }}</strong>
      </p>
      <p>Length: {{ results.length + thickn * 2 }}</p>
      <p>Width: {{ results.width + thickn * 2 }}</p>
      <p>Height: {{ results.height + thickn * 4 }}</p>
      <p><strong>Format: </strong>{{ calculateFormat() }}</p>
    </div>
  </div>
</template>

<style scoped>
.results {
  padding: 50px;
  transition: opacity 2s ease-in-out;
}
</style>

// src/components/BoxResults/BoxResults.tsx
import React from 'react'
import { useDimensions } from '../../context/DimensionsContext'
import { useBoxStyle } from '../../context/BoxStyleContext'
import { useThickness } from '../../context/ThicknessContext'
import { useFormValid } from '../../context/FormValidContext'
import styles from './BoxResults.module.css'

const BoxResults: React.FC = () => {
  const { dimensions } = useDimensions()
  const { thickness } = useThickness()
  const { boxStyle } = useBoxStyle()
  const { formValid } = useFormValid()

  const { length, width, height } = dimensions

  // Helper function to calculate flap height based on material thickness
  const calculateFlapHeight = (): number => {
    if (thickness === 5) {
      return width / 2 + 4
    } else if (thickness === 4) {
      return width / 2 + 2
    } else {
      return width / 2 + 1
    }
  }
  // Blank Size Format Calculation based on Box Style and Thickness
  // +38 = 40 for glueFlap and -2 from length at the end
  const calculateFormat = (): string => {
    const flapHeight = calculateFlapHeight()
    const boxLength = length + width + thickness * 2 // Box length calculation

    let format: string
    switch (boxStyle) {
      case 'box':
        format = `${boxLength * 2 + 38} x ${
          height + (thickness + flapHeight) * 2
        }`
        break
      case 'box-open':
        format = `${boxLength * 2 + 38} x ${height + thickness + flapHeight}`
        break
      case 'half':
        format = `${boxLength + 40} x ${height + (thickness + flapHeight) * 2}`
        break
      case 'half-open':
        format = `${boxLength + 40} x ${height + thickness + flapHeight}`
        break
      default:
        format = `${boxLength * 2 + 38} x ${
          height + (thickness + flapHeight) * 2
        }`
    }
    return format
  }

  // Dummy function for material - This should return a string based on thickness
  const getMat = (): string => {
    switch (thickness) {
      case 5:
        return 'BC'
      case 4:
        return 'C'
      case 3:
        return 'B'
      case 10:
        return 'AAC'
      default:
        return 'Unknown'
    }
  }

  return (
    <div
      className={styles.resultsSection}
      style={{ opacity: formValid ? 1 : 0 }}
    >
      <div className=''>
        <h3 className={styles.heading}>Outer Dimensions</h3>
        <p>Length: {length + thickness * 2} mm</p>
        <p>Width: {width + thickness * 2} mm</p>
        <p>Height: {height + thickness * 4} mm</p>
      </div>

      <p>
        <strong>Material: {getMat()}</strong>
      </p>
      <p>
        <strong>Format: </strong>
        {calculateFormat()} mm
      </p>
    </div>
  )
}

export default BoxResults
